-- MySQL Script generated by MySQL Workbench
-- Tue Dec 19 18:34:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SummerCamps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SummerCamps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SummerCamps` DEFAULT CHARACTER SET utf8 ;
USE `SummerCamps` ;

-- -----------------------------------------------------
-- Table `SummerCamps`.`Activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SummerCamps`.`Activity` (
  `idActivity` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  PRIMARY KEY (`idActivity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SummerCamps`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SummerCamps`.`Region` (
  `idRegion` INT NOT NULL,
  `Name` VARCHAR(60) NULL,
  `Surface` INT(5) NULL,
  `Inhabitants` INT(9) NULL,
  PRIMARY KEY (`idRegion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SummerCamps`.`Holiday Camp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SummerCamps`.`Holiday Camp` (
  `Reference` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Capacity` TINYINT(4) NULL,
  `Region_idRegion` INT NOT NULL,
  PRIMARY KEY (`Reference`, `Region_idRegion`),
  INDEX `fk_Holiday Camp_Region1_idx` (`Region_idRegion` ASC),
  CONSTRAINT `fk_Holiday Camp_Region1`
    FOREIGN KEY (`Region_idRegion`)
    REFERENCES `SummerCamps`.`Region` (`idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SummerCamps`.`Children`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SummerCamps`.`Children` (
  `idCard` INT NOT NULL,
  `Firstname` VARCHAR(60) NULL,
  `LastName` VARCHAR(60) NULL,
  `Holiday Camp_Reference` INT NULL,
  `Holiday Camp_Region_idRegion` INT NULL,
  `Region_idRegion` INT NULL,
  PRIMARY KEY (`idCard`),
  INDEX `fk_Children_Holiday Camp1_idx` (`Holiday Camp_Reference` ASC, `Holiday Camp_Region_idRegion` ASC),
  INDEX `fk_Children_Region1_idx` (`Region_idRegion` ASC),
  CONSTRAINT `fk_Children_Holiday Camp1`
    FOREIGN KEY (`Holiday Camp_Reference` , `Holiday Camp_Region_idRegion`)
    REFERENCES `SummerCamps`.`Holiday Camp` (`Reference` , `Region_idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Children_Region1`
    FOREIGN KEY (`Region_idRegion`)
    REFERENCES `SummerCamps`.`Region` (`idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SummerCamps`.`Activity_has_Holiday Camp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SummerCamps`.`Activity_has_Holiday Camp` (
  `Activity_idActivity` INT NOT NULL,
  `Holiday Camp_Reference` INT NOT NULL,
  PRIMARY KEY (`Activity_idActivity`, `Holiday Camp_Reference`),
  INDEX `fk_Activity_has_Holiday Camp_Holiday Camp1_idx` (`Holiday Camp_Reference` ASC),
  INDEX `fk_Activity_has_Holiday Camp_Activity_idx` (`Activity_idActivity` ASC),
  CONSTRAINT `fk_Activity_has_Holiday Camp_Activity`
    FOREIGN KEY (`Activity_idActivity`)
    REFERENCES `SummerCamps`.`Activity` (`idActivity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_has_Holiday Camp_Holiday Camp1`
    FOREIGN KEY (`Holiday Camp_Reference`)
    REFERENCES `SummerCamps`.`Holiday Camp` (`Reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
